# Generated by Django 5.1.2 on 2024-10-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vxod', '0003_alter_animal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('Author', models.CharField(max_length=50, verbose_name='Автор')),
                ('Publication', models.IntegerField(max_length=50, verbose_name='Год издания')),
            ],
        ),
        migrations.CreateModel(
            name='Book_read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_received', models.DateField(max_length=50, verbose_name='Дата выдачи')),
                ('Data_refund', models.DateField(max_length=50, verbose_name='Дата возврата')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('Birthday', models.DateField(max_length=50, verbose_name='Дата рождения')),
                ('Number_phone', models.IntegerField(max_length=50, verbose_name='Номер телефона')),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
